version: '3'
# https://docs.docker.com/compose/compose-file/
# support Docker version 17.05.0-ce
services:

#################################### crowd ######################################################

##############################
# jira_crowd_mysql
##############################
  jira_crowd_mysql:
    image: "idoall/mysql:5.7"
    hostname: jira_crowd_mysql
    ports:
     - "6033:3306"
    volumes:
      - /Users/lion/my_project/_docker/github_idoall/ubuntu16.04-jira-crowd/3.3.2/my.ini:/etc/mysql/my.cnf
    networks:
      - crowd
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=crowd
      - MYSQL_USER=crowd
      - MYSQL_PASSWORD=crowd_mshk
      - character-set-server=utf8mb4
      - collation-server=utf8mb4_bin
    deploy:
      replicas: 1
      update_config:
        delay: 1s
      restart_policy:
        condition: on-failure
##############################
# jira_crowd
##############################
  jira_crowd:
    image: "idoall/ubuntu16.04-jira-crowd:3.3.2"
    hostname: jira_crowd
    ports:
     - "80:8095"
    networks:
      - crowd
    depends_on:
     - jira_crowd_mysql
    deploy:
      replicas: 1
      update_config:
        delay: 1s
      restart_policy:
        condition: on-failure

# 统一网络设置
networks:
  crowd:
    driver: overlay
