version: "3"
# https://docs.docker.com/compose/compose-file/
# support Docker version 17.05.0-ce
services:

#################################### gitlab ######################################################

##############################
# mshk_gitlab
##############################
  mshk_gitlab:
    image: idoall/gitlab-ce:11.4.6-ce.0
    hostname: mshk_gitlab
    ports:
      - "20052:22"
      - "20050:80"
      - "20051:443"
    networks:
      - mshk
    deploy:
      replicas: 1
      update_config:
        delay: 1s
      restart_policy:
        condition: on-failure


# 统一网络设置
networks:
  mshk:
    driver: overlay
